pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - check-success=Scala CI (JDK 11)
      - check-success=Scala CI (JDK 26)
    actions:
      merge:
        method: merge
  - name: automatically merge dependabot's PRs
    conditions:
      - author=dependabot[bot]
      - check-success=Scala CI (JDK 11)
      - check-success=Scala CI (JDK 26)
    actions:
      merge:
        method: merge
