pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Scala CI
    actions:
      merge:
        method: merge
  - name: automatically merge dependabot's PRs
    conditions:
      - author=dependabot[bot]
      - status-success=Scala CI
    actions:
      merge:
        method: merge
