pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Scala CI
      - body~=labels:.*semver-patch.*
    actions:
      merge:
        method: merge
