version = "3.10.7"
runner.dialect = scala3

maxColumn = 170

indent.main = 2
indent.callSite = 2
indent.defnSite = 2

align.preset = some
align.tokens."+" = [
  { code = "=>", owner = "Case" }
  { code = "->", owner = "Term.ApplyInfix" }
]
align.arrowEnumeratorGenerator = true

newlines.topLevelStatementBlankLines = [
  { blanks = 1 }
]

danglingParentheses.preset = true

rewrite.rules = [SortImports, RedundantBraces, RedundantParens]
rewrite.redundantBraces.stringInterpolation = true

project.excludeFilters = [
  "cornichon-docs"
]

fileOverride {
  "glob:**/scala-2/**" {
    runner.dialect = scala213
  }
  "glob:**/src/main/scala-2/**" {
    runner.dialect = scala213
  }
  "glob:**/src/main/scala-3/**" {
    runner.dialect = scala3
  }
}
