laika.navigationOrder = [
  landing-page.md
  overview.md
  quick-start.md
  dsl
  syntax
  common-patterns.md
  feature-options.md
  test-output.md
  custom-steps
  reference-configuration.md
  property-based-testing
  performance-tuning.md
  troubleshooting.md
  misc.md
]
